apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio-dev

spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`minio.saturn.universe.home`)
    kind: Rule
    services:
    - name: minio
      namespace: minio-dev
      port: 9001
