name: Terraform deploy
on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{vars.AWS_SECRET_ACCESS_KEY}}

jobs:
  deploy:
    runs-on: "self-hosted"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: init
        run: |
          terraform init
      - name: fmt
        run: |
          terraform fmt
      - name: plan
        run: |
          terraform plan -out deployment
      - name: deploy
        run: |
          terraform apply "deployment"
